/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as RegisterIndexRouteImport } from './routes/register.index'
import { Route as RegisterIndividualRouteImport } from './routes/register.individual'
import { Route as RegisterSchoolRouteImport } from './routes/register.school'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndividualRoute = RegisterIndividualRouteImport.update({
  id: '/register/individual',
  path: '/register/individual',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSchoolRoute = RegisterSchoolRouteImport.update({
  id: '/register/school',
  path: '/register/school',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/$slug': typeof EventsSlugRoute
  '/register/individual': typeof RegisterIndividualRoute
  '/register/school': typeof RegisterSchoolRoute
  '/events/': typeof EventsIndexRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/$slug': typeof EventsSlugRoute
  '/register/individual': typeof RegisterIndividualRoute
  '/register/school': typeof RegisterSchoolRoute
  '/events': typeof EventsIndexRoute
  '/register': typeof RegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/$slug': typeof EventsSlugRoute
  '/register/individual': typeof RegisterIndividualRoute
  '/register/school': typeof RegisterSchoolRoute
  '/events/': typeof EventsIndexRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events/$slug'
    | '/register/individual'
    | '/register/school'
    | '/events/'
    | '/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events/$slug'
    | '/register/individual'
    | '/register/school'
    | '/events'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/events/$slug'
    | '/register/individual'
    | '/register/school'
    | '/events/'
    | '/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsSlugRoute: typeof EventsSlugRoute
  RegisterIndividualRoute: typeof RegisterIndividualRoute
  RegisterSchoolRoute: typeof RegisterSchoolRoute
  EventsIndexRoute: typeof EventsIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/individual': {
      id: '/register/individual'
      path: '/register/individual'
      fullPath: '/register/individual'
      preLoaderRoute: typeof RegisterIndividualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/school': {
      id: '/register/school'
      path: '/register/school'
      fullPath: '/register/school'
      preLoaderRoute: typeof RegisterSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsSlugRoute: EventsSlugRoute,
  RegisterIndividualRoute: RegisterIndividualRoute,
  RegisterSchoolRoute: RegisterSchoolRoute,
  EventsIndexRoute: EventsIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
